config/routes.rb
Rails.application.routes.draw do
  devise_for :admins ,controllers: {
      sessions: 'admins/sessions'
  }
  devise_for :users, controllers: {
      omniauth_callbacks: "users/omniauth_callbacks",
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
  }

  root to: 'phones#index'

  # get '/carts/:phone_id', to: 'carts#add', as:'add_to_cart'

  resources :phones, only: [:show, :index]
  resources :orders
  resource :carts do
    get ':phone_id', to: 'carts#add', as: :add_to
    get 'remove/:phone_id', to: 'carts#remove', as: :remove_from
  end
  namespace :manages do
    resources :phones, except: [:destroy]
    resources :categories, except: [:destroy]
    resources :orders
  end
  namespace :api do
    namespace :v1 do
      resources :carts, only: [:show]
      resources :phones
    end
  end
  # api
  namespace :api do
    namespace :v1 do
      resources :phones, only: [:show]
    end
  end
end

app/controllers/manages/categories_controller.rb
module Manages
  class CategoriesController < ManagesController
    before_action :set_category, only: [:show, :edit, :update, :destroy]

    def index
      keyword = params[:qcategory]
      @keyword = keyword
      if keyword == nil
        @categories = Category.order('brand_name').page(params[:page]).per(12)
      else
        if keyword == ""
          @categories = Category.order('brand_name').page(params[:page]).per(12)
        else
          @categories = Category.search_by_brand_name(keyword).order('brand_name').page(params[:page]).per(12)
          @count = @categories.total_count
        end
      end
    end

    def show
    end

    def new
      @category = Category.new
    end

    def edit
    end

    def create
      @category = Category.new(category_params)

      if @category.save
        redirect_to manages_categories_path
      else
        @category.errors
        render :new

      end

    end

    def update

      if @category.update(category_params)
        render :edit
      else
        @category.errors
        render :edit
      end

    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:brand_name, :flag)
    end
  end
end

app/controllers/manages/manages_controller.rb
module Manages
  class ManagesController < ApplicationController
    layout 'manages'
    before_action :authenticate_admin!
  end
end

app/controllers/manages/orders_controller.rb
module Manages
  class OrdersController < ManagesController
    def index
      keyword = params[:qorder]
      if keyword==nil
        @carts = Cart.order(:updated_at).page(params[:page]).per(12)
      else
        if keyword == ""
          @carts = Cart.order(:updated_at).page(params[:page]).per(12)
        else
          @carts = Cart.search_by_order(keyword).order(:updated_at).page(params[:page]).per(12)
          @count = @carts.total_count
        end
      end
    end
    def show
      @cart = Cart.find(params[:id])
    end
  end
end

app/controllers/manages/phones_controller.rb
module Manages
  class PhonesController < ManagesController
    before_action :set_phone, only: [:show, :edit, :update, :destroy]

    def index
      category = Category.find_by_id(params[:id])
      keyword = params[:qphone]
      @category = category
      @keyword = keyword
      if keyword == nil
        if category == nil
          @phones = Phone.order('name').page(params[:page]).per(12)
        else
          @phones = category.phones.order('name').page(params[:page]).per(12)
        end
      else
        if keyword == ""
          @phones = Phone.order('name').page(params[:page]).per(12)
        else
          @phones = Phone.search_by_name(keyword).order('name').page(params[:page]).per(12)
          @count = @phones.total_count
        end
      end
    end

    def show
    end

    def new
      @phone = Phone.new
    end

    def edit
    end

    def create
      @phone = Phone.new(phone_params)

        if @phone.save
            redirect_to [:manages,@phone]
        else
            @phone.errors
            render :new

        end

    end

    def update

        if @phone.update(phone_params)
          render :edit
        else
          @phone.errors
          render :edit
        end

    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_phone
      @phone = Phone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phone_params
      params.require(:phone).permit(:name, :price, :photo_url, :description ,:display, :os, :back_camera,
                                    :font_camera, :cpu, :ram, :storage, :sp_storage, :sim, :battery, :category_id, :flag)
    end
  end
end

app/controllers/manages/users_controller.rb
module Manages
  class UsersController < ManagesController
    def index
      @users = User.page(params[:page]).per(12)
    end
    def show
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  def index
    curren_user_id = current_user.id
    @carts = Cart.where(user_id: curren_user_id).page(params[:page]).per(12)
  end
  def new
    @cart = Cart.find_by(id: session[:cart_id])
  end
  def create
    curren_user_id = current_user.id
    cart = Cart.find_by(id: session[:cart_id])
    cart.update(user_id:curren_user_id,status:1 )
    cart.save
    session[:cart_id] = nil
    redirect_to orders_path
  end

end

app/views/manages/orders/index.html.erb
<div class="manage-index">
  <div class="tools col-md-12">
    <div class="col-md-12">
      <form method="get" action="<%= manages_orders_path %>" id="search">
        <input class="search-term" name="qorder" type="text" size="40" placeholder="Search for order..." value="<%= @keyword %>"/>
        <button type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
        <button class="reset-btn"><i class="fa fa-times" aria-hidden="true"></i></button>
      </form>
    </div>
    <div class="search_message col-md-3">
      <% if @keyword != nil && @keyword != "" %>
          <% if @count == 0 %>
              <div class="text">NO MATCHES FOUND!</div>
          <% else %>
              <% if @count == 1 %>
                  <div class="text">Result for
                    <span class="keyword">"<%= @keyword %>"</span>
                    <span class="count">(<%= @count %>)</span>
                  </div>
              <% else %>
                  <div class="text">Results for
                    <span class="keyword">"<%= @keyword %>"</span>
                    <span class="count">(<%= @count %>)</span>
                  </div>
              <% end %>
          <% end %>
      <% end %>
    </div>
  </div>
  <div class="tables">
    <table class="table table-bordered table-striped">
      <thead>
      <tr>
        <th class="colume-name">Order #</th>
        <th class="colume-name">Custommer Name</th>
        <th class="colume-name">Created At</th>
        <th class="colume-name">Total</th>
        <th class="colume-name">Status</th>
        <th colspan="1" class="colume-name">Action</th>
      </tr>
      </thead>
      <tbody>
      <% @carts.each do |cart| %>
          <tr>
            <td class="colume-text-center"><%= cart.id %></td>
            <td class="colume-text-center">
              <% if cart.user.nil? %>
                  #####
              <% else %>
                  <%= cart.user.name %></td>
              <% end %>
              <td class="colume-text-center"><%= cart.updated_at.getlocal.strftime("%d/%m/%Y %H:%M:%S %Z") %></td>
              <td class="colume-text-center"><%= number_to_currency(cart.total_price, delimiter: "", format: "%n %u") %></td>
              <td class="colume-text-center">
                <% if cart.status==true %>
                    Completed
                <% else %>
                    Incomplete
                <% end %>
              </td>
              <td class="colume-action">
                <%= link_to manages_order_path(cart.id), method: :get do %>
                <button type="button" class="btn btn-success">Details</button>
                <%end %>
              </td>
              </td>
              </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="pagination-container hidden-xs pull-right">
    <nav>
      <%= paginate @carts, :window => 2, theme: 'large' %>
    </nav>
  </div>
  <div class="pagination-container visible-xs text-center">
    <%= paginate @carts, :window => 2, theme: 'normal' %>
  </div>
  <script>
    $(function () {
      $('.reset-btn').click(function () {
        var term = $(this).siblings('.search-term');
        term.val('');
      })
    })
  </script>
</div>

app/views/manages/orders/show.html.erb
<div class="order-details-index">
  <div class="order-details">
    <div class="order-detail-name">Order #<%= @cart.id %> Details</div>
    <div class="order-detail-cus-name">Custommer Name:
      <% if @cart.user==nil %>
          #####
      <% else %>
          <%= @cart.user.name %></div>
      <% end %>
    <div class="order-detail-date">Created Date : <%= @cart.updated_at.getlocal.strftime("%B %d %Y") %></div>
    <div class="order-detail-time">Created At: <%= @cart.updated_at.getlocal.strftime("%H:%M:%S %Z") %></div>
  </div>
  <% if @cart.cart_lines==0 %>
      <div>This cart has no item</div>
  <% else %>
      <div class="tables">
        <table class="table table-bordered table-striped">
          <thead>
          <tr>
            <th class="colume-name">#</th>
            <th class="colume-name">Name</th>
            <th class="colume-name">Added At</th>
            <th class="colume-name">Price</th>
            <th class="colume-name">Quantity</th>
            <th class="colume-name">Sub Total</th>
          </tr>
          </thead>
          <tbody>
          <% @cart.cart_lines.each do |cart_line| %>
              <tr>
                <td>#</td>
                <td class="phone_name"><%= link_to cart_line.phone.name, manages_phone_path(cart_line.phone) %></td>
                <td><%= cart_line.created_at.getlocal.strftime("%d/%m/%Y %H:%M:%S %Z") %></td>
                <td><%= number_to_currency(cart_line.price , delimiter: "", format: "%n %u")%></td>
                <td><%= cart_line.quantity %></td>
                <td><%= number_to_currency(cart_line.price * cart_line.quantity,delimiter: "", format: "%n %u") %></td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
  <% end %>
  <div class="order-details-total">Total :<%= number_to_currency(@cart.total_price , delimiter: "", format: "%n %u")%></div>
  <div class="order-details-back">
      <%= link_to manages_orders_path do %>
          <button type="button" class="btn btn-success">Manage Order</button>
      <%end %>
  </div>
</div>