config/routes.rb
Rails.application.routes.draw do
  devise_for :admins ,controllers: {
      sessions: 'admins/sessions'
  }
  devise_for :users, controllers: {
      omniauth_callbacks: "users/omniauth_callbacks",
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
  }

  root to: 'phones#index'

  # get '/carts/:phone_id', to: 'carts#add', as:'add_to_cart'

  resources :phones, only: [:show, :index]
  resources :orders
  resource :carts do
    get ':phone_id', to: 'carts#add', as: :add_to
    get 'remove/:phone_id', to: 'carts#remove', as: :remove_from
  end
  namespace :manages do
    resources :phones, except: [:destroy]
    resources :categories, except: [:destroy]
    resources :orders
  end
  namespace :api do
    namespace :v1 do
      resources :carts, only: [:show]
      resources :phones
    end
  end
  # api
  namespace :api do
    namespace :v1 do
      resources :phones, only: [:show]
    end
  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_many :cart_lines
  include PgSearch
  pg_search_scope :search_by_order, :associated_against => {:user => [:name]}, :against => :id,
                  :using => {:tsearch => {:prefix => true}}

  def add(phone)

    if cart_lines.count == 0
      create_new_cart_line(phone)
    else
      if cart_line = has_cart_lines_got_phone(phone)
         cart_line.quantity += 1
         cart_line.save
      else
        create_new_cart_line(phone)
      end
    end
  end


  def num_of_phone

    result = 0
    if cart_lines.count > 0
      cart_lines.each do |cart_line|
        result = result + cart_line.quantity
      end
    end
    return result
  end

  def remove(phone)
    if cart_lines.count != 0
      cart_line = has_cart_lines_got_phone(phone)
      if cart_line.quantity > 1
        cart_line.quantity -= 1
        cart_line.save
      else cart_line.quantity = 1
         cart_line.destroy
      end


    end
  end
  def total_price
    total = 0
    #
    if cart_lines.count > 0
      cart_lines.each do |cart_line|
        total_price = cart_line.quantity * cart_line.phone.price
        total = total + total_price
      end
    end
    return total

    end



  private


  def create_new_cart_line(phone)
    cart_lines.create phone: phone, price: phone.price, quantity: 1
  end

  def has_cart_lines_got_phone(phone)
    cart_lines.each do |cart_line|

      if cart_line.phone.id == phone.id
        return cart_line
      end
    end
    nil
  end
end

app/controllers/api/v1/carts_controller.rb
module Api
  module V1
    class CartsController < ApplicationController

      def add
        phone = Phone.find(params[:phone_id])
        @cart = Cart.find_by(id: session[:cart_id])
        @cart = current_cart
        @cart.add(phone)

        respond_to do |format|
          format.html { redirect_to carts_path }
          format.js { render :add }
        end

      end

      def remove
        phone = Phone.find(params[:phone_id])
        @cart = Cart.find_by(id: session[:cart_id])

        if @cart != nil
          @cart.remove(phone)
          respond_to do |format|
            format.js { render :add }
          end
        end

      end

      def show
        @cart = current_cart
      end

      private
      def current_cart
        @cart = Cart.where(id: session[:cart_id]).first
        @cart = Cart.create if @cart.nil?
        session[:cart_id] = @cart.id
        @cart
      end
    end
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def add
    id = params[:id]
    #neu cart da dc tao thi,tao ra mot cart khac de add phone
      if session[:cart] then
        cart = session[:cart]
      else
        session[:cart] = {}
        cart = session[:cart]
      end
    #neu phone da dc add
      if cart[id] then
        cart[id] = cart[id] + 1
      else
        cart[id] = 1
      end
    redirect_to :action => :index
  end
  def clearCart
    session[:cart] = nil
    redirect_to :action => :index
  end


  def index
    if session[:cart] then
      @cart = session[:cart]
    else
      @cart = {}


  end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def add
    phone = Phone.find(params[:phone_id])
    @cart = Cart.find_by(id: session[:cart_id])
    @cart = current_cart
    @cart.add(phone)

    respond_to do |format|
      format.html { redirect_to carts_path }
      format.js { render :add }
    end

  end

  def remove
    phone = Phone.find(params[:phone_id])
    @cart = Cart.find_by(id: session[:cart_id])

    if @cart != nil
      @cart.remove(phone)
      respond_to do |format|
        format.js { render :add }
      end
    end

  end

  def show
      @cart = current_cart
  end

  private
    def current_cart
      @cart = Cart.where(id: session[:cart_id]).first
      @cart = Cart.create if @cart.nil?
      session[:cart_id] = @cart.id
      @cart
    end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/carts/_cart_show.html.erb
<div class="total col-xs-12 col-sm-12 col-md-12">
  <div class="sum-of-phone col-xs-8 col-sm-8 col-md-8">
    <span class="badge">Your Cart: <%= Cart.find_by(id: session[:cart_id]).num_of_phone %></span>
  </div>
  <div class="sum-of-price col-xs-4 col-sm-4 col-md-4">
    <span class="badge"><%= @cart.total_price %>$</span>
  </div>
</div>
<div class="list_cart_line col-xs-12 col-sm-12 col-md-12">

  <% if Cart.find_by(id: session[:cart_id]).num_of_phone==0 %>
      <div class="empty-cart col-xs-12">Your cart is currently empty</div>
  <% else %>
      <% @cart.cart_lines.order('id').each do |cart_line| %>
          <div class="show-container col-xs-12 col-sm-12 col-md-12">
            <div class="phone_img col-xs-4 col-sm-6 col-md-4">
              <%= link_to phone_path(cart_line) do %>
                  <img class="phone-img" src="<%= cart_line.phone.photo_url %>">
              <% end %>
            </div>
            <div class="phone_details col-xs-8 col-sm-6 col-md-8">
              <div class="phone-name col-xs-12 col-sm-12 col-md-12" data-toggle="tooltip" title="<%= cart_line.phone.name %>">
                <%= link_to cart_line.phone.name, phone_path(cart_line) %>
              </div>
              <div class="phone-price col-xs-12 col-sm-12 col-md-12"><%= number_to_currency cart_line.phone.price, precision: 0 %>
                x <%= cart_line.quantity %>
              </div>
              <div class="add-remove col-xs-12 col-sm-12 col-md-12">

                <div class="col-xs-1 col-sm-1 col-md-1"> <%= link_to add_to_carts_path(phone_id: cart_line.phone.id), remote: true do %>
                      <i class="fa fa-plus " aria-hidden="true"></i>
                  <% end %>
                </div>
                <div class="col-xs-1 col-sm-1 col-md-1"> <%= link_to remove_from_carts_path(phone_id: cart_line.phone.id), remote: true do %>
                      <i class="fa fa-minus " aria-hidden="true"></i>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
      <% end %>
      <div class="checkout col-xs-12">
        <%= link_to new_order_path, method: :get do %>
            <button type="button" class="btn btn-success">Checkout</button>
        <% end %>
      </div>
  <% end %>
</div>
<div class="back-to-shopping col-xs-12">
  <%= link_to root_path do %>
      <button type="button" class="btn btn-success">Back To Shopping</button>
  <% end %>
</div>

app/views/carts/add.js.erb
$('.navigation .badge').html('<%= @cart.num_of_phone %>');
$(".carts-show").html('<%= j render 'cart_show' %>');

app/views/carts/show.html.erb
<div class="carts-show col-xs-12">
  <%= render 'cart_show' %>
</div>