config/routes.rb
Rails.application.routes.draw do
  devise_for :admins ,controllers: {
      sessions: 'admins/sessions'
  }
  devise_for :users, controllers: {
      omniauth_callbacks: "users/omniauth_callbacks",
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
  }

  root to: 'phones#index'

  # get '/carts/:phone_id', to: 'carts#add', as:'add_to_cart'

  resources :phones, only: [:show, :index]
  resources :orders
  resource :carts do
    get ':phone_id', to: 'carts#add', as: :add_to
    get 'remove/:phone_id', to: 'carts#remove', as: :remove_from
  end
  namespace :manages do
    resources :phones, except: [:destroy]
    resources :categories, except: [:destroy]
    resources :orders
  end
  namespace :api do
    namespace :v1 do
      resources :carts, only: [:show]
      resources :phones
    end
  end
  # api
  namespace :api do
    namespace :v1 do
      resources :phones, only: [:show]
    end
  end
end

app/models/phone.rb
class Phone < ActiveRecord::Base
  belongs_to :category
  include PgSearch
  pg_search_scope :search_by_name, :against => [:name, :price], :associated_against => {:category => [:brand_name]},
                  :using => {:tsearch => {:prefix => true}}
  validates :name, :photo_url, :price, :category_id, presence: true
  validates :name, length:{minimum: 2, maximum: 100}, uniqueness:true
  validates :price , numericality: {greater_than: 0}
  validates :description , length:{minimum: 20}
end

app/controllers/api/v1/phones_controller.rb
module Api
  module V1
    class PhonesController < ApplicationController
      def index
        category = Category.find_by_id(params[:id])
        keyword = params[:q]
        @category = category
        @keyword = keyword
        if keyword == nil
          if category == nil
            @phones = Phone.order('name').where(flag: true).page(params[:page]).per(12)
          else
            @phones = category.phones.order('name').where(flag: true).page(params[:page]).per(12)
          end
        else
          if keyword == ""
            @phones = Phone.order('name').where(flag: true).page(params[:page]).per(12)
          else
            @phones = Phone.search_by_name(keyword).order('name').where(flag: true).page(params[:page]).per(12)
            @count = @phones.total_count
          end
        end
      end

      def show
        @phone = Phone.find(params[:id])

        respond_to do |format|
          format.json
        end
      end
    end
  end
end

app/controllers/manages/categories_controller.rb
module Manages
  class CategoriesController < ManagesController
    before_action :set_category, only: [:show, :edit, :update, :destroy]

    def index
      keyword = params[:qcategory]
      @keyword = keyword
      if keyword == nil
        @categories = Category.order('brand_name').page(params[:page]).per(12)
      else
        if keyword == ""
          @categories = Category.order('brand_name').page(params[:page]).per(12)
        else
          @categories = Category.search_by_brand_name(keyword).order('brand_name').page(params[:page]).per(12)
          @count = @categories.total_count
        end
      end
    end

    def show
    end

    def new
      @category = Category.new
    end

    def edit
    end

    def create
      @category = Category.new(category_params)

      if @category.save
        redirect_to manages_categories_path
      else
        @category.errors
        render :new

      end

    end

    def update

      if @category.update(category_params)
        render :edit
      else
        @category.errors
        render :edit
      end

    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:brand_name, :flag)
    end
  end
end

app/controllers/manages/manages_controller.rb
module Manages
  class ManagesController < ApplicationController
    layout 'manages'
    before_action :authenticate_admin!
  end
end

app/controllers/manages/orders_controller.rb
module Manages
  class OrdersController < ManagesController
    def index
      keyword = params[:qorder]
      if keyword==nil
        @carts = Cart.order(:updated_at).page(params[:page]).per(12)
      else
        if keyword == ""
          @carts = Cart.order(:updated_at).page(params[:page]).per(12)
        else
          @carts = Cart.search_by_order(keyword).order(:updated_at).page(params[:page]).per(12)
          @count = @carts.total_count
        end
      end
    end
    def show
      @cart = Cart.find(params[:id])
    end
  end
end

app/controllers/manages/phones_controller.rb
module Manages
  class PhonesController < ManagesController
    before_action :set_phone, only: [:show, :edit, :update, :destroy]

    def index
      category = Category.find_by_id(params[:id])
      keyword = params[:qphone]
      @category = category
      @keyword = keyword
      if keyword == nil
        if category == nil
          @phones = Phone.order('name').page(params[:page]).per(12)
        else
          @phones = category.phones.order('name').page(params[:page]).per(12)
        end
      else
        if keyword == ""
          @phones = Phone.order('name').page(params[:page]).per(12)
        else
          @phones = Phone.search_by_name(keyword).order('name').page(params[:page]).per(12)
          @count = @phones.total_count
        end
      end
    end

    def show
    end

    def new
      @phone = Phone.new
    end

    def edit
    end

    def create
      @phone = Phone.new(phone_params)

        if @phone.save
            redirect_to [:manages,@phone]
        else
            @phone.errors
            render :new

        end

    end

    def update

        if @phone.update(phone_params)
          render :edit
        else
          @phone.errors
          render :edit
        end

    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_phone
      @phone = Phone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phone_params
      params.require(:phone).permit(:name, :price, :photo_url, :description ,:display, :os, :back_camera,
                                    :font_camera, :cpu, :ram, :storage, :sp_storage, :sim, :battery, :category_id, :flag)
    end
  end
end

app/controllers/manages/users_controller.rb
module Manages
  class UsersController < ManagesController
    def index
      @users = User.page(params[:page]).per(12)
    end
    def show
    end
  end
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  def index
    category = Category.find_by_id(params[:id])
    keyword = params[:q]
    @category = category
    @keyword = keyword
    if keyword == nil
      if category == nil
        @phones = Phone.order('name').where(flag: true).page(params[:page]).per(12)
      else
        @phones = category.phones.order('name').where(flag: true).page(params[:page]).per(12)
      end
    else
      if keyword == ""
        @phones = Phone.order('name').where(flag: true).page(params[:page]).per(12)
      else
        @phones = Phone.search_by_name(keyword).order('name').where(flag: true).page(params[:page]).per(12)
        @count = @phones.total_count
      end
    end
  end

  def show
    @phone = Phone.find(params[:id])
  end
end

app/views/manages/phones/_form.html.erb
<div class="manage-show">
  <%= form_for [:manages, @phone] do |f| %>
      <div class="phone-index">
        <div type class="phone-name">
          <span class="name"><%= f.text_field :name, placeholder: "Phone Name" %></span>
        </div>
        <div class="row">
          <div class="phone-image col-xs-12 col-sm-6 col-md-4">
            <img class="image" src="<%= @phone.photo_url %>">
            <span><%= f.text_field :photo_url, placeholder: "Photo Url" %></span>
          </div>
          <div class="small-description col-xs-12 col-sm-6 col-md-3">
            <div class="phone-option">
              <div><%= f.select :category_id, Category.all.collect {|c| [c.brand_name, c.id]}  %></div>
              <div><%= f.text_field :price, placeholder: "Price" %></div>
              <div class="col-md-3">Visible</div>
              <div class="col-md-1"><%= f.check_box :flag %></div>
            </div>
          </div>
          <div class="errors-message col-xs-12 col-sm-6 col-md-5">
            <% if @phone.errors.any? %>
                <div class="error_explanation">
                    <% @phone.errors.full_messages.each do |message| %>
                        <div><%= message %></div>
                    <% end %>
                </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="phone-desciption">
        <div class="row">
          <div class="description col-xs-10 col-sm-2 col-md-2 ">
            <span>Description </span>
          </div>
          <div class="col-xs-2 col-sm-1 col-sm-push-9 col-md-1 col-md-push-9" style="margin-top: 15px">
            <span class="collapse-button fa fa-chevron-down" data-toggle="collapse" data-target="#des" aria-hidden="true"></span>
          </div>
          <div id="des" class=" collapse in col-xs-12 col-sm-9 col-sm-pull-1 col-md-9 col-md-pull-1">
            <span><%= f.text_area :description, placeholder: "Description for phone" %></span>
          </div>
        </div>
      </div>
      <div class="phone-specifiction">
        <div class="row">
          <div class="specification col-xs-10 col-sm-2 col-md-2">
            <span>Specification</span>
          </div>
          <div class="col-xs-2 col-sm-1 col-sm-push-9 col-md-1 col-md-push-9" style="margin-top: 15px">
            <span class="collapse-button fa fa-chevron-down" data-toggle="collapse" data-target="#param" aria-hidden="true"></span>
          </div>
          <div id="param" class="collapse in col-xs-12 col-sm-9 col-sm-pull-1 col-md-9 col-md-pull-1">
            <div class="parameters">
              <div class="field col-xs-12 col-sm-12 col-md-12">
                <div class="key col-xs-6 col-sm-6 col-md 4">Display</div>
                <div class="col-xs-6 col-sm-6 col-md 8"><%= f.text_field :display %></div>
              </div>
              <div class="field col-xs-12 col-sm-12 col-md-12">
                <div class="key col-xs-6 col-sm-6 col-md 4">Operating System</div>
                <div class="col-xs-6 col-sm-6 col-md 8"><%= f.text_field :os %></div>
              </div>
              <div class="field col-xs-12 col-sm-12 col-md-12">
                <div class="key col-xs-6 col-sm-6 col-md 4">Back Camera</div>
                <div class="col-xs-6 col-sm-6 col-md 8"><%= f.text_field :back_camera %></div>
              </div>
              <div class="field col-xs-12 col-sm-12 col-md-12">
                <div class="key col-xs-6 col-sm-6 col-md 4">Font-Camera</div>
                <div class="col-xs-6 col-sm-6 col-md 8"><%= f.text_field :font_camera %></div>
              </div>
              <div class="field col-xs-12 col-sm-12 col-md-12">
                <div class="key col-xs-6 col-sm-6 col-md 4">CPU</div>
                <div class="col-xs-6 col-sm-6 col-md 8"><%= f.text_field :cpu %></div>
              </div>
              <div class="field col-xs-12 col-sm-12 col-md-12">
                <div class="key col-xs-6 col-sm-6 col-md 4">Ram</div>
                <div class="col-xs-6 col-sm-6 col-md 8"><%= f.text_field :ram %></div>
              </div>
              <div class="field col-xs-12 col-sm-12 col-md-12">
                <div class="key col-xs-6 col-sm-6 col-md 4">Storage</div>
                <div class="col-xs-6 col-sm-6 col-md 8"><%= f.text_field :storage %></div>
              </div>
              <div class="field col-xs-12 col-sm-12 col-md-12">
                <div class="key col-xs-6 col-sm-6 col-md 4">Support Memory Card</div>
                <div class="col-xs-6 col-sm-6 col-md 8"><%= f.text_field :sp_storage %></div>
              </div>
              <div class="field col-xs-12 col-sm-12 col-md-12">
                <div class="key col-xs-6 col-sm-6 col-md 4">Sim</div>
                <div class="col-xs-6 col-sm-6 col-md 8"><%= f.text_field :sim %></div>
              </div>
              <div class="field col-xs-12 col-sm-12 col-md-12">
                <div class="key col-xs-6 col-sm-6 col-md 4">Battery</div>
                <div class="col-xs-6 col-sm-6 col-md 8"><%= f.text_field :battery %></div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="submit"><%= f.submit %></div>
  <% end %>
</div>

app/views/manages/phones/edit.html.erb
<div class="manage-edit">
  <div class="page-title">Update Phone</div>
  <%= render 'form' %>
</div>
<div>
  <div class="navigate-button col-md-2">
    <%= link_to [:manages,@phone] do %>
        <button type="button" class="btn btn-success">Preview</button>
    <%end %>
  </div>
  <div class="navigate-button col-md-2">
    <%= link_to manages_phones_path do %>
        <button type="button" class="btn btn-success">Manages</button>
    <%end %>
  </div>
</div>

app/views/manages/phones/index.html.erb
<div class="manage-index">
  <div class="tools col-md-12">
    <div class="dropdown col-md-2">
      <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Browse
        <span class="caret"></span></button>
      <ul class="dropdown-menu">
        <li><%= link_to('All Phone', manages_phones_path) %></li>
        <% Category.all.each do |category| %>
            <li><%= link_to(category.brand_name, manages_phones_path(id: category.id)) %></li>
        <% end %>
      </ul>
    </div>
    <div class="col-md-2">
      <%= link_to new_manages_phone_path do %>
          <button type="button" class="btn btn-success">Add new Phone</button>
      <% end %>
    </div>
    <div class="col-md-5">
      <form method="get" action="<%= manages_phones_path %>" id="search">
        <input class="search-term" name="qphone" type="text" size="40" placeholder="Search for phone..." value="<%= @keyword %>"/>
        <button type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
        <button class="reset-btn"><i class="fa fa-times" aria-hidden="true"></i></button>
      </form>
    </div>
    <div class="search_message col-md-3">
      <% if @keyword != nil && @keyword != "" %>
          <% if @count == 0 %>
              <div class="text">NO MATCHES FOUND!</div>
          <% else %>
              <% if @count == 1 %>
                  <div class="text">Result for
                    <span class="keyword">"<%= @keyword %>"</span>
                    <span class="count">(<%= @count %>)</span>
                  </div>
              <% else %>
                  <div class="text">Results for
                    <span class="keyword">"<%= @keyword %>"</span>
                    <span class="count">(<%= @count %>)</span>
                  </div>
              <% end %>
          <% end %>
      <% end %>
    </div>
  </div>
  <div class="tables">
    <table class="table table-bordered table-striped">
      <thead>
      <tr>
        <th class="colume-name">Phone Name</th>
        <th class="colume-name">Brand Name</th>
        <th class="colume-name">Price</th>
        <th class="colume-name">Date Created</th>
        <th class="colume-name">Date Modifed</th>
        <th class="colume-name">Visible</th>
        <th colspan="2" class="colume-name">Action</th>
      </tr>
      </thead>
      <tbody>
      <% @phones.each do |phone| %>
          <tr>
            <td class="colume-value"><%= link_to phone.name, phone_path(phone), :target => 'blank' %></td>
            <td><%= phone.category.brand_name %></td>
            <td class="colume-text-center"><%= number_to_currency(phone.price, delimiter: "", format: "%n %u") %></td>
            <td class="colume-text-center"><%= phone.created_at.getlocal.strftime("%d/%m/%Y %H:%M:%S %Z") %></td>
            <td class="colume-text-center"><%= phone.updated_at.getlocal.strftime("%d/%m/%Y %H:%M:%S %Z") %></td>

            <% if phone.flag == true %>
                <td class="colume-checkbox"><input type="checkbox" checked onclick="return false;" readonly="readonly">
                </td>
            <% else %>
                <td class="colume-checkbox">
                  <input type="checkbox" unchecked onclick="return false;" readonly="readonly"></td>
            <% end %>
            <td class="colume-action"><%= link_to manages_phone_path(phone) do %>
                  <button type="button" class="btn btn-success">Preview</button>
              <% end %>
            </td>
            <td class="colume-action"><%= link_to edit_manages_phone_path(phone) do %>
                  <button type="button" class="btn btn-success">Update</button>
              <% end %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="pagination-container hidden-xs pull-right">
    <nav>
      <%= paginate @phones, :window => 2, theme: 'large' %>
    </nav>
  </div>
  <div class="pagination-container visible-xs text-center">
    <%= paginate @phones, :window => 2, theme: 'normal' %>
  </div>
  <script>
    $(function() {
      $('.reset-btn').click(function() {
        var term = $(this).siblings('.search-term');
        term.val('');
      })
    })
  </script>
</div>

app/views/manages/phones/new.html.erb
<div class="manage-new">
  <div class="page-title">Add New Phone</div>
  <%= render 'form' %>
</div>
<div>
  <div class="navigate-button col-md-2">
    <%= link_to manages_phones_path do %>
        <button type="button" class="btn btn-success">Manages Phone</button>
    <%end %>
  </div>
</div>

app/views/manages/phones/show.html.erb
<div class="manage-show">
  <div class="phone-index">
    <div type class="phone-name">
      <span class="name"><%= @phone.name %></span>
    </div>
    <div class="row">
      <div class="phone-image col-xs-12 col-sm-6 col-md-4">
        <img class="image" src="<%= @phone.photo_url %>">
      </div>
      <div class="small-description col-xs-12 col-sm-6 col-md-4">
        <div class="phone-option">
          <button type="button" class="price-button btn btn-default"><%= number_to_currency @phone.price, precision: 0 %>
            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
          </button>
        </div>
      </div>
    </div>
  </div>
  <div class="phone-desciption">
    <div class="row">
      <div class="description col-xs-10 col-sm-2 col-md-2 ">
        <span>Description </span>
      </div>
      <div class="col-xs-2 col-sm-1 col-sm-push-9 col-md-1 col-md-push-9" style="margin-top: 15px">
        <span class="collapse-button fa fa-chevron-down" data-toggle="collapse" data-target="#des" aria-hidden="true"></span>
      </div>
      <div id ="des" class=" collapse in col-xs-12 col-sm-9 col-sm-pull-1 col-md-9 col-md-pull-1">
      <span><%= @phone.description %>
      </span>
      </div>
    </div>
  </div>
  <div class="phone-specifiction">
    <div class="row">
      <div class="specification col-xs-10 col-sm-2 col-md-2">
        <span>Specification</span>
      </div>
      <div class="col-xs-2 col-sm-1 col-sm-push-9 col-md-1 col-md-push-9" style="margin-top: 15px">
        <span class="collapse-button fa fa-chevron-down" data-toggle="collapse" data-target="#param" aria-hidden="true"></span>
      </div>
      <div id="param"class="collapse in col-xs-12 col-sm-9 col-sm-pull-1 col-md-9 col-md-pull-1">
        <div class="parameters">
          <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="key col-xs-6 col-sm-6 col-md 4">Display</div>
            <div class="col-xs-6 col-sm-6 col-md 8"><%= @phone.display %></div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="key col-xs-6 col-sm-6 col-md 4">Operating System</div>
            <div class="col-xs-6 col-sm-6 col-md 8"><%= @phone.os %></div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="key col-xs-6 col-sm-6 col-md 4">Back Camera</div>
            <div class="col-xs-6 col-sm-6 col-md 8"><%= @phone.back_camera %></div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="key col-xs-6 col-sm-6 col-md 4">Font-Camera</div>
            <div class="col-xs-6 col-sm-6 col-md 8"><%= @phone.font_camera %></div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="key col-xs-6 col-sm-6 col-md 4">CPU</div>
            <div class="col-xs-6 col-sm-6 col-md 8"><%= @phone.cpu %></div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="key col-xs-6 col-sm-6 col-md 4">Ram</div>
            <div class="col-xs-6 col-sm-6 col-md 8"><%= @phone.ram %></div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="key col-xs-6 col-sm-6 col-md 4">Storage</div>
            <div class="col-xs-6 col-sm-6 col-md 8"><%= @phone.storage %></div>
          </div >
          <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="key col-xs-6 col-sm-6 col-md 4">Support Memory Card</div>
            <div class="col-xs-6 col-sm-6 col-md 8"><%= @phone.sp_storage %></div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="key col-xs-6 col-sm-6 col-md 4">Sim</div>
            <div class="col-xs-6 col-sm-6 col-md 8"><%= @phone.sim %></div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="key col-xs-6 col-sm-6 col-md 4">Battery</div>
            <div class="col-xs-6 col-sm-6 col-md 8"><%= @phone.battery %></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div>
    <div class="navigate-button col-md-2">
      <%= link_to edit_manages_phone_path do %>
          <button type="button" class="btn btn-success">Update Phone</button>
      <%end %>
    </div>
    <div class="navigate-button col-md-2">
      <%= link_to manages_phones_path do %>
          <button type="button" class="btn btn-success">Manges Phone</button>
      <%end %>
    </div>
  </div>
</div>