config/routes.rb
Rails.application.routes.draw do
  devise_for :admins ,controllers: {
      sessions: 'admins/sessions'
  }
  devise_for :users, controllers: {
      omniauth_callbacks: "users/omniauth_callbacks",
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
  }

  root to: 'phones#index'

  # get '/carts/:phone_id', to: 'carts#add', as:'add_to_cart'

  resources :phones, only: [:show, :index]
  resources :orders
  resource :carts do
    get ':phone_id', to: 'carts#add', as: :add_to
    get 'remove/:phone_id', to: 'carts#remove', as: :remove_from
  end
  namespace :manages do
    resources :phones, except: [:destroy]
    resources :categories, except: [:destroy]
    resources :orders
  end
  namespace :api do
    namespace :v1 do
      resources :carts, only: [:show]
      resources :phones
    end
  end
  # api
  namespace :api do
    namespace :v1 do
      resources :phones, only: [:show]
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Phonestore</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= growlyflash_static_notices %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <link rel="manifest" href="assets/manifest.json">
</head>
<body>
<div class="navigation">
  <div class="left">
    <%= link_to root_path, class:"homeclick" do %>
        <i class="fa fa-mobile" aria-hidden="true"></i>
        <span class="name">PhoneStore</span>
    <% end %>
    <!--Thanh Search khong hien thi tren Mobile-->
    <div class="search hidden-xs">
      <form method="get" action="<%= phones_path %>" id="search">
        <input name="q" type="text" size="40" placeholder="Search..." value="<%= @keyword %>"/>
      </form>
    </div>
  </div>
  <div class="right">
    <!--Chi danh cho giao dien Ipad-->
    <div class="signin-signout hidden-xs">
      <% if user_signed_in? %>
          <div class="dropdown">
            <button class="fa fa-user-o hidden-xs dropdown-toggle" type="button"
                    id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            </button>
            <div class="dropdown-menu pull-left" aria-labelledby="dropdownMenu1">
              <div role="separator" class="divider">Hi <%= current_user.name %></div>
              <div><%= link_to('Profile', edit_user_registration_path)  %></div>
              <div><%= link_to('Order history', orders_path)  %></div>
              <div><%= link_to('Sign out', destroy_user_session_path, :method => :delete) %></div>
            </div>
          </div>
      <% else %>

            <%= link_to('SIGN IN', '#', 'data-toggle':"modal", class:"signin-btn", 'data-target':"#myModal" ) %>
            <!-- Modal -->
            <div id="myModal" class="modal fade" role="dialog">
              <div class="modal-dialog modal-sm">
                <!-- Modal content-->
                <div class="modal-content">
                  <div class="modal-body signin-container-new">
                    <%= render 'devise/sessions/login_form', resource: User.new, resource_name: :user %>
                  </div>
                </div>
              </div>
            </div>

      <% end %>
    </div>
    <%= link_to carts_path, method: :get do %>
      <i class="fa fa-shopping-cart hidden-xs hidden-lg" aria-hidden="true">
        <% if Cart.find_by(id: session[:cart_id]).nil? %>
            <span class="badge">0</span>
        <% else %>
            <span class="badge"><%= Cart.find_by(id: session[:cart_id]).num_of_phone %></span>
        <%end  %>
      </i>
    <% end %>

    <div class="dropdown">
      <button class="fa fa-bars visible-sm dropdown-toggle" type="button"
              id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
      </button>
      <div class="dropdown-menu pull-left" aria-labelledby="dropdownMenu1">
        <div><%= link_to('All categories', root_path, class:'All categories')  %></div>
        <% Category.all.each do |category| %>
            <div><%= link_to( category.brand_name, root_path(id:category.id), class:'')  %></div>
        <% end %>
      </div>
    </div>
    <!--Chi danh cho giao dien Mobile-->
    <div class="dropdown">
      <button class="fa fa-bars visible-xs dropdown-toggle" type="button"
              id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
      </button>
      <div class="dropdown-menu pull-left" aria-labelledby="dropdownMenu1">
        <div class="search_for_mobile visible-xs">
          <form method="get" action="<%= phones_path %>" id="search">
            <input class="ss" name="q" type="text" size="40" placeholder="Search..." value="<%= @keyword %>"/>
          </form>
        </div>
        <div role="separator" class="divider">BROWSE</div>
        <div><%= link_to('All categories', root_path, class:'All categories')  %></div>
        <% Category.all.each do |category| %>
            <div><%= link_to( category.brand_name, root_path(id:category.id), class:'')  %></div>
        <% end %>

        <div class="sign-in-sign-out">
          <% if user_signed_in? %>
              <div role="separator" class="divider">Hi <%= current_user.name %></div>
              <div><%= link_to('Profile', edit_user_registration_path)  %></div>
              <div><%= link_to('Order history', orders_path)  %></div>
              <div><%= link_to('Sign out', destroy_user_session_path, :method => :delete) %></div>
          <% else %>
              <div role="separator" class="divider">GUEST</div>
              <div><%= link_to('Sign in', new_user_session_path)  %></div>
              <div><%= link_to "Sign up",new_user_registration_path %></div>
          <% end %>
        </div>
      </div>
    </div>
    <%= link_to carts_path, method: :get do %>
      <i class="fa fa-shopping-cart hidden-sm hidden-md" aria-hidden="true">
        <% if Cart.find_by(id: session[:cart_id]).nil? %>
            <span class="badge">0</span>
        <% else %>
            <span class="badge"><%= Cart.find_by(id: session[:cart_id]).num_of_phone %></span>
        <%end  %>
      </i>
    <% end %>
    <!--Chi danh cho giao dien Destop(Large)-->
    <span class="dropdown">
      <button class="browse hidden-xs hidden-sm" type="button"
              id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">BROWSE
      </button>
      <div class="dropdown-menu pull-left" aria-labelledby="dropdownMenu1">
        <div><%= link_to('All categories', root_path, class:'All categories')  %></div>
        <% Category.all.each do |category| %>
            <div><%= link_to( category.brand_name, root_path(id:category.id), class:'')  %></div>
        <% end %>
      </div>
    </span>
  </div>
  <div class="clearfix"></div>
  <%= yield :category_bar %>
</div>

<div class="container">
  <%= yield %>
</div>
<div class="bottom">
  <h1>Follow Us</h1>
  <div class="social-li">
    <a target="_blank" href="https://www.facebook.com/">
      <i class="fa fa-facebook" aria-hidden="true"></i>
    </a>
    <a target="_blank" href="https://www.twitter.com/">
      <i class="fa fa-twitter" aria-hidden="true"></i>
    </a>
    <a target="_blank" href="https://www.plus.google.com/">
      <i class="fa fa-google-plus" aria-hidden="true"></i>
    </a>
    <a target="_blank" href="https://www.pinterest.com/">
      <i class="fa fa-pinterest" aria-hidden="true"></i>
    </a>
    <a target="_blank" href="https://www.instagram.com/">
      <i class="fa fa-instagram" aria-hidden="true"></i>
    </a>
    <a target="_blank" href="https://www.youtube.com/">
      <i class="fa fa-youtube" aria-hidden="true"></i>
    </a>
  </div>
  <h2>2016 © PhoneStore</h2>
</div>
</body>
</html>

app/views/layouts/hidenav.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Phonestore</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= growlyflash_static_notices %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <link rel="manifest" href="assets/manifest.json">

</head>
<body>
<div class="navigation">
  <div class="left">
    <%= link_to root_path, class:"homeclick" do %>
        <i class="fa fa-mobile" aria-hidden="true"></i>
        <span class="name">PhoneStore</span>
    <% end %>
  </div>
  <div class="right">
    <span class="signin-signout sign-in-button">
      <a href="/users/sign_in" style="color:white;">SIGN IN</a>
    </span>
  </div>
  <div class="clearfix"></div>
</div>

<div class="container">
  <%= yield %>
</div>
<div class="bottom">
  <h1>Follow Us</h1>
  <div class="social-li">
    <a target="_blank" href="https://www.facebook.com/">
      <i class="fa fa-facebook" aria-hidden="true"></i>
    </a>
    <a target="_blank" href="https://www.twitter.com/">
      <i class="fa fa-twitter" aria-hidden="true"></i>
    </a>
    <a target="_blank" href="https://www.plus.google.com/">
      <i class="fa fa-google-plus" aria-hidden="true"></i>
    </a>
    <a target="_blank" href="https://www.pinterest.com/">
      <i class="fa fa-pinterest" aria-hidden="true"></i>
    </a>
    <a target="_blank" href="https://www.instagram.com/">
      <i class="fa fa-instagram" aria-hidden="true"></i>
    </a>
    <a target="_blank" href="https://www.youtube.com/">
      <i class="fa fa-youtube" aria-hidden="true"></i>
    </a>
  </div>
  <h2>2016 © PhoneStore</h2>
</div>
</body>
</html>

app/views/layouts/manages.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Phones Store Management</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <link rel="manifest" href="assets/manifest.json">

</head>
<body>
<div class="navigation">
  <div class="left">
    <%= link_to manages_phones_path, class:"homeclick" do %>
        <i class="fa fa-mobile" aria-hidden="true"></i>
        <span class="name">Phone Store Management</span>
    <% end %>
    <!--Thanh Search khong hien thi tren Mobile-->
  </div>
  <div class="right">
    <!--Chi danh cho giao dien Ipad-->
    <!--Chi danh cho giao dien Mobile-->
    <!--Chi danh cho giao dien Destop(Large)-->
    <% if admin_signed_in? %>
        <span class="manage-navigtion"><%= link_to destroy_admin_session_path, :method => :delete do %>
          <i class="fa fa-sign-out" aria-hidden="true"></i>
              <%end  %>
        </span>
    <%end  %>
    <span class="manage-navigtion"><%= link_to 'Manage Orders', manages_orders_path %></span>
    <span class="manage-navigtion"><%= link_to 'Manage Brand', manages_categories_path %></span>
    <span class="manage-navigtion"><%= link_to 'Manage Phones', manages_phones_path %></span>
  </div>
  <div class="clearfix"></div>
  <%= yield :category_bar %>
</div>

<div class="container">
  <%= yield %>
</div>
<div class="bottom-manges">
</div>
</body>
</html>